# Cloudflare Workers 配置文件
name = "word-teacher-backend"
main = ".mastra/output/index.mjs"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

# 生产环境配置
[env.production]
name = "word-teacher-backend"
main = ".mastra/output/index.mjs"

# 环境变量（在 Cloudflare Dashboard 中设置）
# OPENAI_API_KEY: OpenAI API 密钥

# 资源限制
[limits]
cpu_ms = 50000

# 自定义域名配置（可选）
# [[route]]
# pattern = "lkkblog7.top/api/*"
# zone_name = "lkkblog7.top"