name = "word-teacher-backend"
# 主要入口点：Mastra构建输出路径
main = ".mastra/output/index.mjs"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

# Account ID 将从环境变量中读取，而不是硬编码
# account_id 会从 CLOUDFLARE_ACCOUNT_ID 环境变量中获取

# Node.js兼容性设置
[build]
command = ""

# 生产环境配置
[env.production]
name = "word-teacher-backend"
vars = { NODE_ENV = "production" }

# CPU 限制已移除 - 免费计划不支持自定义 CPU 限制
# Cloudflare 免费计划将使用默认限制

# 环境变量说明：
# CLOUDFLARE_ACCOUNT_ID - 通过 GitHub Secrets 设置
# CLOUDFLARE_API_TOKEN - 通过 GitHub Secrets 设置
# OPENAI_API_KEY - 将在 Worker 部署后通过 Dashboard 设置