name = "word-teacher-backend"
# 主要入口点：Mastra构建输出路径
main = ".mastra/output/index.mjs"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

# Node.js兼容性设置
[build]
command = ""

[env.production]
name = "word-teacher-backend"

[vars]
NODE_ENV = "production"

# 环境变量通过 GitHub Actions secrets 设置
# OPENAI_API_KEY
# CLOUDFLARE_API_TOKEN  
# CLOUDFLARE_ACCOUNT_ID

# Workers 资源限制
[limits]
cpu_ms = 10000
