name = "word-teacher-backend"
# 主要入口点：Mastra构建输出路径
main = ".mastra/output/index.mjs"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

# 确保使用正确的 Account ID
account_id = "3ab6ad05b43923cfa5ba2e6de82b2c86"

# Node.js兼容性设置
[build]
command = ""

# 生产环境配置
[env.production]
name = "word-teacher-backend"
vars = { NODE_ENV = "production" }

# Workers 资源限制
[limits]
cpu_ms = 10000

# 环境变量说明：
# OPENAI_API_KEY - 将通过 wrangler secret 或 dashboard 设置