name = "word-teacher-backend"
main = "dist/index.js"
compatibility_date = "2024-01-01"
node_compat = true

[env.production]
name = "word-teacher-backend"

[vars]
NODE_ENV = "production"

# 环境变量配置（敏感信息通过 GitHub Secrets 和 Cloudflare Workers 环境变量设置）
# OPENAI_API_KEY = "your-openai-api-key" # 通过 wrangler secret 设置

# 自定义域名（如果需要）
# [[routes]]
# pattern = "api.your-domain.com/*"
# zone_name = "your-domain.com"

# Workers 资源限制
[limits]
cpu_ms = 10000
