name = "word-teacher-backend"
# 主要入口点：Mastra构建成功时使用.mastra/index.mjs，失败时使用dist/index.js
main = ".mastra/index.mjs"
compatibility_date = "2024-01-01"
node_compat = true

# Node.js兼容性设置
[build]
command = ""

[build.upload]
format = "modules"

[env.production]
name = "word-teacher-backend"

[vars]
NODE_ENV = "production"

# 环境变量通过 GitHub Actions secrets 设置
# OPENAI_API_KEY
# CLOUDFLARE_API_TOKEN  
# CLOUDFLARE_ACCOUNT_ID

# Workers 资源限制
[limits]
cpu_ms = 10000
